### ISSUE TITLE
ImportErrors in body_visualizer

### ISSUE THREAD

**Issue by gngdb** [facebookresearch/fairmotion#63]
These two lines appear to try and import things that don't exist. There is no `colors` in `human_body_prior.tools.omni_tools` and `MeshViewer` isn't in `human_body_prior`, it's used in that repository but it's from `body_visualizer` [here](https://github.com/nghorbani/body_visualizer/blob/master/src/body_visualizer/mesh/mesh_viewer.py#L37).

https://github.com/facebookresearch/fairmotion/blob/ac0e06b984cfe53ef96a6a773fcc2e08ea733dfc/fairmotion/viz/body_visualizer.py#L31-L32

**Comment by gngdb** [comment]
Changing it to import from `body_visualizer` fails because the file is called `body_visualizer.py`. Renaming it fixes this.

`BodyModel` is also used later in this file and is never imported.

**Comment by VimalMollyn** [comment]
Were you able to get it to work? I still had a matmul error after fixed the bugs you mentioned.

**Comment by gngdb** [comment]
No I ended up with libGL errors and gave up. I wrote the Motions to `.bvh` files and then opened them in blender to render.

**Comment by dpacgopinath** [comment]
@gngdb @VimalMollyn thanks for the bug report! It looks like a lot of things changed with `human_body_prior` project. Since we had not used a link to a fixed commit/tag in our setup, the `body_visualizer` tool stopped working. I have fixed these in https://github.com/facebookresearch/fairmotion/pull/71 and verified that visualization works. Apologies for the delayed response. Feel free to post issues about the libGL and matmul errors too.

**Comment by VimalMollyn** [comment]
> @gngdb @VimalMollyn thanks for the bug report! It looks like a lot of things changed with `human_body_prior` project. Since we had not used a link to a fixed commit/tag in our setup, the `body_visualizer` tool stopped working. I have fixed these in #71 and verified that visualization works. Apologies for the delayed response. Feel free to post issues about the libGL and matmul errors too.

Thanks! Will give it a try soon! :D
