### ISSUE TITLE
Install script is broken: torch 1.6.0 is no longer supported by pip

### ISSUE THREAD

**Issue by lucasribeiroufrj** [facebookresearch/fairmotion#74]
torch 1.6.0 is no longer supported by pip, only 1.7.1+

**Comment by dpacgopinath** [comment]
The torch version was fixed (as opposed to using latest) because changing versions broke training in one of the tasks. Could you point me to the source of this information, or post error message? I see `torch==1.6.0` is still supported by pip, on linux and mac.

```
On mac:
Collecting torch==1.6.0
  Downloading torch-1.6.0-cp37-none-macosx_10_9_x86_64.whl (97.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 MB 26.9 MB/s eta 0:00:00
On linux:
Collecting torch==1.6.0
  Downloading torch-1.6.0-cp38-cp38-manylinux1_x86_64.whl (748.8 MB)
     |████████████████████████████████| 748.8 MB 100.0 MB/s
```
The [pip page](https://pypi.org/project/torch/1.6.0/) and [PyTorch page](https://pytorch.org/get-started/previous-versions/#linux-and-windows-11) don't indicate that it's not supported either.

That said, we should consider changing `torch` version to the latest, but with lower priority and making sure we don't break any of the `tasks`.

**Comment by ameliacode** [comment]
```
pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
This will help

**Comment by lucasribeiroufrj** [comment]
Usin

> ```
> pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html --user
> ```
> 
> 
>     
>  
>   
> 
> This will help

Unfortunately it did not help. I'm using pip 22.0.4 and python 3.9 on MacOS. The error is the following:
```
pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html --user
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.6.0+cpu (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.6.0+cpu
```
